# CMake generated Testfile for 
# Source directory: /home/sunil/git/lvgl/lvgl_cpp
# Build directory: /home/sunil/git/lvgl/lvgl_cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_chart_table "/home/sunil/git/lvgl/lvgl_cpp/test_chart_table")
set_tests_properties(test_chart_table PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;210;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_tabview "/home/sunil/git/lvgl/lvgl_cpp/test_tabview")
set_tests_properties(test_tabview PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;233;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_span "/home/sunil/git/lvgl/lvgl_cpp/test_span")
set_tests_properties(test_span PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;237;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_api_hardening "/home/sunil/git/lvgl/lvgl_cpp/test_api_hardening")
set_tests_properties(test_api_hardening PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;241;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_image "/home/sunil/git/lvgl/lvgl_cpp/test_image")
set_tests_properties(test_image PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;247;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_msgbox_win "/home/sunil/git/lvgl/lvgl_cpp/test_msgbox_win")
set_tests_properties(test_msgbox_win PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;253;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_animation_timeline "/home/sunil/git/lvgl/lvgl_cpp/test_animation_timeline")
set_tests_properties(test_animation_timeline PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;258;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_menu "/home/sunil/git/lvgl/lvgl_cpp/test_menu")
set_tests_properties(test_menu PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;262;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_core_widgets "/home/sunil/git/lvgl/lvgl_cpp/test_core_widgets")
set_tests_properties(test_core_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;271;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_input_widgets "/home/sunil/git/lvgl/lvgl_cpp/test_input_widgets")
set_tests_properties(test_input_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;272;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_complex_widgets "/home/sunil/git/lvgl/lvgl_cpp/test_complex_widgets")
set_tests_properties(test_complex_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;273;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_visual_widgets "/home/sunil/git/lvgl/lvgl_cpp/test_visual_widgets")
set_tests_properties(test_visual_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;274;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(observer_test "/home/sunil/git/lvgl/lvgl_cpp/observer_test")
set_tests_properties(observer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;275;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_ownership "/home/sunil/git/lvgl/lvgl_cpp/test_ownership")
set_tests_properties(test_ownership PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;276;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_animation "test_animation")
set_tests_properties(test_animation PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;277;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_fluent_api "/home/sunil/git/lvgl/lvgl_cpp/test_fluent_api")
set_tests_properties(test_fluent_api PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;278;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_group "/home/sunil/git/lvgl/lvgl_cpp/test_group")
set_tests_properties(test_group PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;279;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_rotation "/home/sunil/git/lvgl/lvgl_cpp/test_rotation")
set_tests_properties(test_rotation PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;280;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_event_system "/home/sunil/git/lvgl/lvgl_cpp/test_event_system")
set_tests_properties(test_event_system PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;281;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_draw_task "/home/sunil/git/lvgl/lvgl_cpp/test_draw_task")
set_tests_properties(test_draw_task PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;282;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_file_system "/home/sunil/git/lvgl/lvgl_cpp/test_file_system")
set_tests_properties(test_file_system PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;283;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_geometry "/home/sunil/git/lvgl/lvgl_cpp/test_geometry")
set_tests_properties(test_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;284;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_screen "/home/sunil/git/lvgl/lvgl_cpp/test_screen")
set_tests_properties(test_screen PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;285;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_input_device "/home/sunil/git/lvgl/lvgl_cpp/test_input_device")
set_tests_properties(test_input_device PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;286;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_lottie "/home/sunil/git/lvgl/lvgl_cpp/test_lottie")
set_tests_properties(test_lottie PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;290;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_vector "/home/sunil/git/lvgl/lvgl_cpp/test_vector")
set_tests_properties(test_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;294;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_api_expansion "/home/sunil/git/lvgl/lvgl_cpp/test_api_expansion")
set_tests_properties(test_api_expansion PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;299;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_obj_proxies "/home/sunil/git/lvgl/lvgl_cpp/test_obj_proxies")
set_tests_properties(test_obj_proxies PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;303;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_core_api_phase9 "/home/sunil/git/lvgl/lvgl_cpp/test_core_api_phase9")
set_tests_properties(test_core_api_phase9 PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;307;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_fluent_styles "/home/sunil/git/lvgl/lvgl_cpp/test_fluent_styles")
set_tests_properties(test_fluent_styles PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;311;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_enums "/home/sunil/git/lvgl/lvgl_cpp/test_enums")
set_tests_properties(test_enums PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;315;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_font "/home/sunil/git/lvgl/lvgl_cpp/test_font")
set_tests_properties(test_font PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;319;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_async "/home/sunil/git/lvgl/lvgl_cpp/test_async")
set_tests_properties(test_async PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;323;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_log "/home/sunil/git/lvgl/lvgl_cpp/test_log")
set_tests_properties(test_log PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;327;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_timer "/home/sunil/git/lvgl/lvgl_cpp/test_timer")
set_tests_properties(test_timer PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;331;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_style_proxy "/home/sunil/git/lvgl/lvgl_cpp/test_style_proxy")
set_tests_properties(test_style_proxy PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;335;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_layout_proxy "/home/sunil/git/lvgl/lvgl_cpp/test_layout_proxy")
set_tests_properties(test_layout_proxy PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;339;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_scroll_proxy "/home/sunil/git/lvgl/lvgl_cpp/test_scroll_proxy")
set_tests_properties(test_scroll_proxy PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;343;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_scale "/home/sunil/git/lvgl/lvgl_cpp/test_scale")
set_tests_properties(test_scale PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;347;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_constants "/home/sunil/git/lvgl/lvgl_cpp/test_constants")
set_tests_properties(test_constants PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;351;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_cast "/home/sunil/git/lvgl/lvgl_cpp/test_cast")
set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;355;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_layout "/home/sunil/git/lvgl/lvgl_cpp/test_layout")
set_tests_properties(test_layout PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;359;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_coverage_sweep "/home/sunil/git/lvgl/lvgl_cpp/test_coverage_sweep")
set_tests_properties(test_coverage_sweep PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;363;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_header_integrity "/usr/bin/python3" "/home/sunil/git/lvgl/lvgl_cpp/scripts/check_headers.py")
set_tests_properties(test_header_integrity PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;367;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
subdirs("lvgl_build")
