# CMake generated Testfile for 
# Source directory: /home/sunil/git/lvgl/lvgl_cpp
# Build directory: /home/sunil/git/lvgl/lvgl_cpp/build_asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_chart_table "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_chart_table")
set_tests_properties(test_chart_table PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;187;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_tabview "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_tabview")
set_tests_properties(test_tabview PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;210;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_image "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_image")
set_tests_properties(test_image PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;216;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_msgbox_win "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_msgbox_win")
set_tests_properties(test_msgbox_win PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;222;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_animation_timeline "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_animation_timeline")
set_tests_properties(test_animation_timeline PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;227;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_menu "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_menu")
set_tests_properties(test_menu PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;231;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_core_widgets "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_core_widgets")
set_tests_properties(test_core_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;240;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_input_widgets "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_input_widgets")
set_tests_properties(test_input_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;241;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_complex_widgets "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_complex_widgets")
set_tests_properties(test_complex_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;242;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_visual_widgets "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_visual_widgets")
set_tests_properties(test_visual_widgets PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;243;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(observer_test "/home/sunil/git/lvgl/lvgl_cpp/build_asan/observer_test")
set_tests_properties(observer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;244;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_ownership "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_ownership")
set_tests_properties(test_ownership PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;245;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_animation "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_animation")
set_tests_properties(test_animation PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;246;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_fluent_api "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_fluent_api")
set_tests_properties(test_fluent_api PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;247;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_group "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_group")
set_tests_properties(test_group PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;248;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_rotation "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_rotation")
set_tests_properties(test_rotation PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;249;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_event_system "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_event_system")
set_tests_properties(test_event_system PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;250;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_draw_task "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_draw_task")
set_tests_properties(test_draw_task PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;251;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_file_system "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_file_system")
set_tests_properties(test_file_system PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;252;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_geometry "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_geometry")
set_tests_properties(test_geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;253;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_screen "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_screen")
set_tests_properties(test_screen PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;254;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_callbacks "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_callbacks")
set_tests_properties(test_callbacks PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;255;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_input_device "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_input_device")
set_tests_properties(test_input_device PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;256;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_fluent_styles "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_fluent_styles")
set_tests_properties(test_fluent_styles PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;260;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_enums "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_enums")
set_tests_properties(test_enums PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;264;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_font "/home/sunil/git/lvgl/lvgl_cpp/build_asan/test_font")
set_tests_properties(test_font PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;268;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
add_test(test_header_integrity "/usr/bin/python3" "/home/sunil/git/lvgl/lvgl_cpp/scripts/check_headers.py")
set_tests_properties(test_header_integrity PROPERTIES  _BACKTRACE_TRIPLES "/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;272;add_test;/home/sunil/git/lvgl/lvgl_cpp/CMakeLists.txt;0;")
subdirs("lvgl_build")
